#+TITLE: Meaning Representations
#+AUTHOR: Atreyee Ghosal

* Why Do We Need Decent Semantic Representations?

The phonological, morphological and syntactic representations that we have studied so far do not work for certain semantic tasks, like:

(1) Inference
(2) Question answering
(3) Using natural language instructions to execute programs

Thus, we need semantic representations- representations that link the linguistic elements present in the texts to the /meaning/ thereof.

** Semantic Analysis

The process whereby we map language input to some sort of meaning structure.

** Existing Meaning Representation Systems

*** First-Order Logic
*** Semantic Network
*** Conceptual Dependency
*** Frame-Based Representations
*** Event Semantics... ?

** Existing Computational Semantic Representation Systems

*** WordNet
*** FrameNet
* A Semantic Representation Framework Should Be

** Verifiable
** Unambiguous

This presents a problem as we're trying to map from the inherent ambiguity of language to an unambiguous representation.

# probabilistic semantic representations?
** Canonical Form

A single canonical form for multiple surface forms.
** Expressiveness
** Inference and Variables
* The /Literal Meaning/ Shortcoming
* Model-Theoretic Semantics

#+BEGIN_QUOTE
objects, properties of objects, and relations among objects

#+END_QUOTE

** Model

#+BEGIN_QUOTE
A formal construct that stands for the state of affairs in the world that we're trying to represent.

#+END_QUOTE
** Terminology of a Model

   - Non-Logical Vocabulary :: labels/names for objects in the world
   - Logical Vocabulary :: symbols, quantifiers, links, keywords, et cetera that compose and operate on the expressions
   - Denotation :: every element of the non-logical vocabulary *denotes*, i.e: corresponds to a fixed and well-defined part of the model
   - Domain Of A Model :: all the objects being represented/thought of 
   - Intentional :: properties are defined by features an object must have to fit that property (necessary&sufficient conditions)
   - Extensional :: properties are defined by sets of objects grouped together

** Truth-Conditional Semantics
