#+TITLE: Homework - 1: Translate and Analyse
#+AUTHOR: Atreyee Ghosal

# key: ~ : acute accent
# key: ` : grave accent
# key: ^ : chapeau

* Original Text

Lizzie was only a week old when all her sisters had started talking.

Although the thought of why she couldn't meow had bothered her several times, she chose to be more optimistic and not talk about it.

Lizzy was from a royal household cat family. They've always been expert mouse hunters. And Lizzy was the weakest of the lot. She was always the more criticized one. But then came the day when everything changed.

The Kat family had evolutionarily upgraded their game. They could now hear vibrations made by cats.

* Translated Text

Lizzie avait seulement une semaine quand toutes ses soeurs a commence~ parler.

Bien que l'idée de ne pas pouvoir miauler la dérangeait à plusieurs reprises, elle choisit e^tre plus optimiste et n'en parle pas. 

Lizzy a e~te~ à une famille de chats domestiques royaux. Ils ont toujours été des chasseurs de souris experts. Et Lizzy était le plus faible du lot. Elle a e~te~ toujours la plus critiquée. Mais alors est venu le jour où tout a changé.

La famille Kat avait évolué de manière évolutive. Ils pouvaient maintenant entendre les vibrations faites par les chats.


* Analysis
