#+TITLE: Environment And Politics in India - 23/03/20
#+AUTHOR: Atreyee Ghosal

Why don't we have a green party in India?

* Examples Of Environmental Movements In India

Think: what would be the weakness in these issues becoming electoral agendas?

** Chipko Movement - April 1973

A contradiction between commercial interests from outside the state, and local interests (fuel, food, fodder, etc.)

"Who is going to give us fodder if we don't have trees"

Was followed by a series of lesser known movements across the country with same M.O - eg: "Apiko movement" in Karnataka

These environmental protests became protests over control of local resources

Look up: Jharkhand Mukti Morcha- when environmental issues get couched as issues about political autonomy

** Ecological Watersheds in India

- Apiko movement, 1980s
- Jharkhand Mukti Morcha - jungle kaato- finish off monocultures in the jungle
  - participants: <look @ slide> people from diveerse economic backgrounds whose livelihood depends on access to forests
- Tendu leaf policy 
  - why does the tendu leaf have political significance: is livelihood of large section of people in chhattisgarh, want good price for it 
    - tendu policy laws allows protection from extortion rackets that exist in chhattisgarh
- draft forest bill of 1982

** Draft Forest Bill scrapping, 1982

Discourse about environmentalism in India is different- pro-peasant, anti-industry, anti-local-enterprise, no local participation

Problem is top-down promotion of policy without active participation of local communities

** Mulshi Satyagraha

http://ramachandraguha.in/archives/the-world%e2%80%99s-first-anti-dam-movement.html

Industrial workers vs. peasant farmers

** Blue Revolution

Artisanal fisherfolk vs: modern trawlers

*** Ganga Mukti Andolan

*** Limestone Mining in the Doon Valley

Why did limestone mining get banned in the Doon valley, and not in, say, Rajasthan? Why did coal mining not get banned elsewhere?

- narrative around coal as a national asset, which is why environmental movements againt coal mining have a hard time

*** Essar Coal Mining

The Priya Pillai case

Govt. of India argument: Greenpeace is working against national interests in India, developed nations keep greenpeace funded so that development can be stymied in developing countries

Environmentalism in India runs up against nationalist/national development narratives

THe track record of the supreme court re: environment has been difficult to pin down, it largely depends on the composition of the bench in that particular case

* Problems w/environmentalism in India

Why did each of these environmentalist movements not gain much power in India?

** Crusading gandhians

TODO: ANSWER: Don't have a narrative to deal with aspirations of youth/oppressed classes

** Appropriate Technologists

Vagueness of demands

** Ecological Marxists

?????

* Jharkhand Mukti Morcha

Closest to becoming a green party that India has seen because of following platforms:

** local participation

pushes for adivasis to be involved in decision making

** jobs for locals
