#+TITLE: Class Notes - 15/2/18
#+AUTHOR: K.M


Today, we'll be looking at some other aspects of discourse.

(Next class, we will see some of the elements of a story)

# oh god I'm so dead - km

* Inferences [contd.]

There are more inferences than discussed in the previous class.

Inferences can be:

(There are other kinds of inferences- more than these)

** Elaborative

When the information in the sentence is less, and we have to infer /more/ information.

Eg: "Tomorrow is my sister's birthday. I have to go to the mall."

Here, we can /infer/ that the speaker has to go to the mall to buy a present, by inference from the sentence, *experience* and *cultural information* .

To explain this more- imagine we had to insert some sentences between the two above sentences:

"Tomorrow is my sister's birthday. I haven't bought her a gift yet. I have to go to the mall."

i.e: (birthday) --[connects to- present- buy {gift}]--> (go to the mall)

Elaborative inference- only if the world knowledge of both the speaker and the hearer match, then it can happepn.

** Restrictive

Suppose there are lots of sentences, and we have to compress the information.

Eg: Suppose we read a book with ~300 sentences, and are asked to summarise it in three sentences. 

i.e: How to restrict all information given to only the /important/ bits of information.

    - We have to understand the whole text before we can summarise it
    - This- understanding the whole text- involves elaborative inferences
    - /After/ elaborative inference, we can summarise the now-understood information
* Local/Global

A text is coherent when it, to put it in layman's terms, /makes sense/.

** Local Coherence

Inter-sentential relationships- coherence within a single discourse.

** Global Coherence

Inter-discourse coherence.

* Discourse

When we talk about discourse, we talk about /text/.

Say, we have a novel, where the author is narrating a story. The author is presenting a /monologue/.
*Within* this monologue, there may be /dialogues/.

** Monologue
** Dialogue
** Human-Character Interaction
* Topics on Discourse

** Coherence and Cohesion

*** Coherence

Example of incoherence: /refer to slide/

We can /connect/ these incoherent sentences by providing some background, but there is no inherent link that we can see just by reading the five sentences.

*** Cohesion

"/Binding/"

** Local and Global Structure
** Micro/Macrostructure
** Context Dependent Situations

*** Referring expressions

Pronouns, definite expressions, etc.
Eg: "Tomorrow is my sister's birthday. I have to go to the mall to buy *her* a gift."
Eg: "I saw *the* man on the road."

*** Universe of Discourse

"Commonly/collectively understood" terms.

Eg: "Every student is hardworking"- generalisation referring to the universe of discourse of the speaker (teacher), not a generalisation over everything in the (earth) world.
   
*** Responses to Questions

Both speaker and hearer should have shared knowledge.

*** Implicit Relationship B/w Events

"Max fell. John pushed him."

The implicit relationship:

(Max fell) --[CAUSE]--> (John pushed him)

*** Ellipsis

Some information is not shared/missing. That information is gathered from the previous sentences.

Eg: "Susan bought a car. So did Mary."

** Factors Influencing Discourse Interpretation

*** Discourse connectives

=and, but, because, so=

Eg: "John took up a job. Bill went to medical school."

=> "John took up a job /and/ Bill went to medical school."
{Parallel events}
=> "John took up a job /but/ Bill went to medical school."
{Maybe Bill was also expected to take up a job?}
=> "John took up a job /because/ Bill went to medical school."
{Maybe John took up a job to pay the bills?}
=> "John took up a job /so/ Bill went to medical school."
{Some other interpretation}
*** Punctuation
*** World Knowledge/Experience

/causal inference/ -> inferrring which one is the cause of the other, based on world knowledge

Eg: "John poisoned bill. He died within a week."
(poison) --[cause]--> (he died)
VS.
Eg: "John poisoned Bill. He was arrested within a week."

(poisoning Bill) --[cause]--> (getting arrested)

*Bridging the inference* - "reading between the lines", so to speak. Some types:

    + Causal inference
    + Spatial Inference
      - Eg: "Mary heard the ice-cream bell. She ran out."
      - Inference: (Where did Mary run from) --> (the house)

*** Tense and Aspect
*** Topic of Discussion/Theme
__________________
|       ^
|      / \
|     /   \
|    /     \
|   /       \
|  /         \    
| /           \
|/             \
/               \
|---------------|
|---------------|
|---------------|
|---------------|
|---------------|
^^^^^^^^^^^^^^^^^
** Discourse/Rhetorical Relations
** Cohesive Devices - Connectives, Pronouns
** Ellipsis

Some information is not given, yet still we understand the discourse.
