#+TITLE: Feature Structure Description
#+AUTHOR: C.A.L


* Feature Structure Desc. of Proper Noun

Syntax-semantics interface- where the syntax is being governed by semantic information.
/ref. to slide on Proper Noun and Verb feature structure description/

** /trans-v-lxm/

Eg: take the verb, "eat"

In the FRAME matrix, the agent of "eat" will be of certain type. That will not type-match, say, "mango".

Therefore we will not be able to form a sentence like "A mango eats a man."

Similarly with the THEME in the frame matrix.

Eg type hierarchy for a transitive verb:

TRANS. V

--> TR1  --> TR11
         --> TR12
--> TR2
--> TR3

* Unification Fails

/refer to slide/

** Note: an /or/ between graph types is not possible

However, we can have an underspecified type in it's space.

* Constructing Semantic Structure of Sentences

We try to automate the process of assigning semantic representations of human languages?

The assumption here, is that we can use compopsitionality to derive the meaning of a sentence. I.e: we can use the meaning of the chunk to get the meaning of the bigger part (sentence).

However, we know that compositionality fails in a lot of cases. Eg: MWEs, idiomatic expressions.


** Unification as a well-formedness constraint-checking operation

# ???

# Wait how will this help the lack of compositionality?

Eg: "Ravi dORega."

(1) Take FSD of "dORa" (run)

Note: in this method, we have to define *all* the constraints. This harkens back to the problem I put up. But we can solve it by defining constraints on *types*, instead of individual verbs.

From this we can go to:

(2) FSD of inflected "dORega"

Referring to presentation, we can see that its FSD has two daughters.

We can see that the type of "dORega" is /fut-word/, as in, it is a *word*, not a lexeme (reminder: a lexeme is a 'headword').

The semantic structure has two matrices for the FRAME feature:

/some-fr/: says nothing but /there exists an event/ of this kind (run)
--> LBL
--> BV (Bound Variable): i.e: what does the verb have scope over
--> RSTR
# Alok: why are we taking an event as a variable anyway?
# Reason: we need to decompose events to refer to subevents, and we cannot decompose predicates
# I cannot record the full answer to the doubt
# TODO: expand this with notes from CSWFP
/fut-fr/: says that this event is in /future/ form

^^ This is based on *Event as a variable* (remember the E marker in verbnet?)
 It also has DTRS (DAUGHTERS) feature, which tells us from which *lexeme* this word has come from. Therefore, we can see the inflected word as a combination of the *lexemes* that form it.

# ENGLISH RESOURCE GRAMMAR- TAKE A LOOK AT IT
# ^ how to machine-learn grammar from the corpus??? once we have a suitably-sized manually-annotated corpus? ERG did it- how?

*** Composition of "ram" and "dORega"

/ref slide/

Type of the full sentence:

/sub-pred-constr/

<-- /word/
<-- /word/

** Why are types so important anyway?

*Types help in compatibility checks* - i.e: we can check with things like "this type does not go with that type"

Eg: in the /subject-predicate-construct/ type we can see that:

(1) It has a valence of /null/
(2) Semantics of it is a combination of semantics of /some-fr/, /fut-fr/, /run-fr/, /entity-fr/

So when the unification of the types in a sentence is successful, we get the semantics of the full sentence/phrase.

THIS BE COMPOSITIONALITY, BITCHES!

Note: order of compositionality does not matter.

* Won't we have infinite thematic roles in the feature matrix for, say, verbs, because we can have near-infinite attachments to a verb in a sentence?

So, we can solve this problem in 2 ways.

One- like framenet, we can do a corpus study and annotate every possible case that can attach to a verb.

Or else- instead of making something as specific as a /trans-verb/ a primitive type, make it a composite type that inherits from sub-types, and put mechanisms for compositionality. Like so-

(1) Have a set of abstract feature sets as types
(2) Have a set of constraints assigned on the composition of types, for well-formedness.

Eg:

INTRANS. V. (primitive type) 
               -[Composition w/constraints]->  TRANS. V (composite type)
THEME (primitive type)
... <we can add more roles here>

# using types in linguistics?
# ah fuck, sexy

** Using Adjuncts Instead?

Does not really work for languages other than english.
* Fish

ASK HER TO SHARE RESOURCES ON EVENT SEMANTICS AND LOGICS THAT REPAIR THE FLAWS OF PREDICATE LOGIC

here have a fish:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~-----~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~/~~~~~\~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~/~~~~~~~\~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~\~~~~~~~/~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~\~~~~~/~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~-----~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
* What do we need to know for the exam

thanks tanmai

Answer: chapter 15, 16, 17

We need to know the /idea/ presented in the slides. Eg question: give a FSD of a common noun? 
