#+TITLE: 19/2/18 - Class Notes
#+AUTHOR: deadciel

# bad processing
# bad language translation

Extra linguistic information from videos? Body language? 

Body language is missing unless transcribed?

But major information about text is that we don't concentrate on extra-textual things. We just analyse the information present in the text itself. Well, text can have limited emotion information: "EXAMPLE ANGER IS PUT IN ALL CAPS"

Transcribing information from video will be a challenge.

There is a field called /conversation analysis/ - subfield of linguistics- that deals with this. All this stuff. Has come out as a separate subfield of discourse analysis, because their methodology is different.

Conversational analysis
    - must have natural data

Also focuses on- mechanisms. Eg:
    - turn taking mechanisms (Speaker A, if talking, has the right to offer the /right to talk/ to anybody)
    - /silence/
    - Adjacency pairs
    - Topic shift
    - Preferred reaction
    - Dispreferred reaction

So, we look at the same thing from two different perspectives in discourse analysis and conversation analysis.


