#+TITLE: CL 2 Class Notes - 25/1/18
#+AUTHOR: KW

* Aim of Computational Semantics

# to be useless

The end goal is semantic representations of human languages. And then use these representations to perform inference and verification of the information.

# and is this really the best way?

Representation should be:

** Computationally Tractable

# no shit

** Canonical 
** Unambiguous
** Verifiable

i.e: it should be possible to determine the relationships between the meaning of a sentence and the world we know.

This includes alias-matching (eg: matching Stanford College and Stanford as same)
# of course, how else would we bloody evaluate it
** Logics Tried

*** First-Order Predicate Logic
*** Modal Logic

Includes tense and modal information.
But this is also not sufficient.

Eg: "I believe that John is good."

This sentence does not necessarily mean that in the absolute world, "John is good" holds. Therefore, we need to consider world-order when we compute the truth of a sentence.

# "Traversing across worlds". hah.

Therefore, we calculate the truth value of a sentence /within a certain frame of reference/. And within that frame of reference, we have to consider entities and the relations between them.

Therefore w.r.t computational semantics, the first thing we have to do is *construct a model*. But we can't just construct one model; multiple models must be constructed to, for example, account for the above sentence.

The structure of all possible worlds will be the same.

# how does one make a world structure

* Meaning Is Notional 

** Note on Fuzziness

People have tried but... it is hard.

# that's what she said

* Some Notes on Sentence Meaning

  - Predicate logic is bad at representing TAM
  - A sentence is not always compositional 
  - We build the meaning step-by-step

For example:

"He is coming tomorrow."

/is/ --> present
/tomorrow/ --> future

Therefore, here
 
* Event-Based Semantic Representation

Event-based flat semantic representation.


X   -----> Entity
    -----> Eventuality ---> Event
                       ---> State

** Philosophy of Language
* Types of Semantic Relations

We propose two kinds of semantic relations:

** Thematic Relations

Relation b/w /eventuality/ and /participants/ involved in the eventuality.

One major criticism of thematic relations is that, one can never have a finite set of relations.

*** Vivaksha

Speaker's intention also matters. When a speaker is speaking, they also decide which information to bring into focus, hide, make implicit, make explicit, etc.

In paninian grammer, we have tried to model this concept of /vivaksha/.

*** Example of Kaaraka

Eg: Maa_KARTA ne bacchi ko chawal *khilaya*

Here, we notice that *one KARMA can be the KARTA of the subevent of the verb*.

/khilaya/ has two tiers of event - (Cause) and (Eat)

Thus:

child --[KARTA]--> eat
chhawal --[KARMA]--> khilana (Eat)
chhawal --[KARMA]--> khilana (cause)
child --[KARMA]--> cause
maa --[KARTA]--> cause

Eg: Ram ne mohan ko sau rupiya me ek kitaab becha.

> Ram ne mohan ko kitaab becha
> Mohan ne ram ko sau rupiya diya

# something about /daan/ and /sampradaan/ ?

/Daan/ is a very lofty idea in Indian semantics, therefore the relation of /sampradaan/. This cannot be used for all and any transactions.

** Non-Thematic Relations
